name: Restart Render Service

on:
  schedule:
    # Выполнять каждый день в 4:00 по Киеву (2:00 UTC)
    - cron: '0 2 * * *'

jobs:
  restart-service:
    runs-on: ubuntu-latest

    steps:
      - name: Send restart request to Render
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            https://api.render.com/v1/services/srv-cu184j56l47c73a1drm0/restart